### ISSUE TITLE
Question about the triplet loss

### ISSUE THREAD

**Issue by shenyanqing1105** [HanjiangHu/DASGIL#7]
In the process of running the train.py, the triplet loss will be 0， is it normal?
![image](https://user-images.githubusercontent.com/34307462/141705879-372e0b2f-422f-47e5-8497-5275a2f0e09f.png)

**Comment by HanjiangHu** [comment]
Thanks for your interest in our work. It may be normal because the distance in the latent space is getting larger for both positive and negative pairs, and it does not influence the final results too much. Maybe you can modify it with other more advanced techniques in contrastive learning and welcome to create pull requests if you find better methods or hyperparameters.
